config/routes.rb
WaysIntoWork::Application.routes.draw do
  devise_for :user_logins, controllers: {sessions: "sessions"}

  devise_scope :user_login do
    root to: "sessions#new"
  end

  get 'hackney_works', to: redirect('/')

  get 'apprenticeships', to: redirect('https://opportunities.hackney.gov.uk/apprentices')
  get 'hackney100' => 'static#hackney100'
  get 'work_placements', to: redirect('https://opportunities.hackney.gov.uk/placements')
  get 'support' => 'static#support'
  get 'employers', to: redirect('https://opportunities.hackney.gov.uk/employers')
  get 'hubs', to: redirect('https://opportunities.hackney.gov.uk/support-2/')
  get 'unsubscribed' => 'static#unsubscribed'

  get 'privacy-policy' => 'static#privacy_policy'

  get 'outside-hackney' => 'static#outside_hackney'
  get 'client/referrers/outside-hackney' => 'static#referrer_outside_hackney', as: 'referrer_outside_hackney'
  get 'just-registered' => 'static#just_registered'

  namespace :advisor do
    resource :restore_client, only: :update
    resource :anonymise_client, only: :update
    resources :clients, except: :edit do
      resources :file_uploads, only: %i[create new destroy]
      resources :meetings
      resources :action_plan_tasks
      resources :contact_notes
      resources :achievements
      #resources :enquiries
      member do
        get 'edit(/:tab)', to: 'clients#edit', as: 'edit'
        #get 'enquiries', to: 'enquiries#for_client'
      end
    end

    resources :my_clients, only: :index
    resources :dashboard, only: :index

    resources :task_titles, only: :index
    resources :advisors
    resources :vacancies
    resources :featured_vacancies, only: %i[update]
    resources :opportunities, only: [] do
      resources :enquiries, only: [:show]
    end
    resources :jobs
    resources :external_apprenticeships
    resources :work_placements
    resources :events, only: [:new, :create, :update, :edit]
    resources :trainings, only: [:new, :create, :update, :edit]
    resources :internal_apprenticeships, only: [:new, :create, :update, :edit]
    resources :enquiries, only: [:index, :show]
    get 'clients/:client_id/enquiries', to: 'enquiries#for_client', as: :client_enquiries
    get 'clients/:client_id/applications', to: 'applications#for_client', as: :client_applications
    
    resources :applications, only: [:index, :show]
    put 'applications/dismiss_all', to: 'applications#dismiss_all', as: :application_dismiss_all
    put 'applications/:id/dismiss', to: 'applications#dismiss', as: :application_dismiss
  end

  resources :clients, only: %i[new create]
  resources :opportunities, only: [:show, :index]

  resources :hubs, only: :index

  namespace :client do
    get 'next_steps' => 'next_steps#show'
    resource :referrers, only: %i[new create]
    resources :file_uploads, only: %i[create new destroy]
    resource :password, only: [:edit]
    resource :profile, only: [:show]
    resources :action_plan_tasks, only: [:show]
    resource :personal_traits, only: %i[edit update]
    resource :objectives, only: %i[edit update]
    resource :education, only: %i[edit update], controller: 'education'
    resource :employment_status, only: %i[edit update], controller: 'employment_status'
    resource :additional_information, only: %i[edit update], controller: 'additional_information'
    resource :dashboard, only: :show
    resources :jobs, only: [:show]
    resources :external_apprenticeships, only: [:show]
    get 'enquiry_confirm' => 'enquiry_confirm#show'
  end

  get '/download/:id', to: 'downloads#download', as: 'download'

  match '/401', to: 'errors#unauthorised', via: :all
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#error', via: :all


  namespace :api do
    namespace :v1 do
      resources :opportunities, only: [:index]
      get 'opportunities/featured' => 'opportunities#featured'
      resources :applications, only: [:create]#, constraints: { protocol: 'https://', host: 'opportunities.hackney.gov.uk' }
    end
  end
end

app/views/eligibility/outside_hackney.html.haml
.column
  %h2.subtitle Do you live within Hackney?

  %p Sorry, based on the post code you provided it looks like you live outside Hackney so we weren’t able to register you online.

  %p You could still be eligible for our service if either of the following apply:
  %ul
    %li You are being housed in Hackney Council temporary accommodation outside the borough.
    %li You have Hackney Council as a corporate parent, i.e. you are or were in care.

  %p
    If so, please call us on
    =link_to "0208 356 5700", "tel:0208 356 5700"
    and we will book you an appointment with an advisor.

  %p If not, try your local council website for information about employment support services in your area.
  %br


  %p If you live in Hackney and are seeing this screen either try registering again and make sure your post code is correct, or you can register over the phone by calling the hub closest to where you live:

  =link_to "Find your local hub", hubs_path, class: "button is-primary"

app/views/eligibility/referrer_outside_hackney.html.haml
.column
  %h2.subtitle Does your referral live within Hackney?
  
  %p Sorry, it looks like this person lives outside Hackney so we weren’t able to complete the referral.
  
  %p They could still be eligible for our service if either of the following apply:
  %ul
    %li They are being housed in Hackney Council temporary accommodation outside the borough.
    %li They have Hackney Council as a corporate parent, i.e. they are or were in care.
  
  %p
    If so, please call us on
    =link_to "0208 356 5700", "tel:0208 356 5700"
    we can process your referral.